# YouTube 트렌드 데이터 자동 수집 (현재 비활성화)
# development:
#   collect_kr_trending:
#     class: CollectTrendingDataJob
#     queue: default
#     args: [ "KR", "all" ]
#     schedule: at 12:00am every day
#     
# production:
#   collect_kr_trending:
#     class: CollectTrendingDataJob
#     queue: default
#     args: [ "KR", "all" ]
#     schedule: at 12:00am every day
    
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
