# YouTube 트렌드 데이터 자동 수집
development:
  collect_all_countries:
    class: CollectAllCountriesJob
    queue: default
    schedule: "0 0 * * * Asia/Seoul"  # 서울 시간 매일 00:00
    
production:
  collect_all_countries:
    class: CollectAllCountriesJob  
    queue: default
    schedule: "0 0 * * * Asia/Seoul"  # 서울 시간 매일 00:00
    
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
